export const top100Cities = [
    "Tokyo,JP", "New York,US", "São Paulo,BR", "Mexico City,MX",
    "Jakarta,ID", "Delhi,IN", "Shanghai,CN", "Manila,PH", "Karachi,PK", "Beijing,CN",
    "Los Angeles,US", "Moscow,RU", "Dhaka,BD", "Cairo,EG", "Osaka,JP", "Bangkok,TH",
    "Buenos Aires,AR", "Kolkata,IN", "Istanbul,TR", "Mumbai,IN", "Lagos,NG", "Lima,PE",
    "Kinshasa,CD", "Ho Chi Minh City,VN", "Bogotá,CO", "Johannesburg,ZA", "Baghdad,IQ",
    "Tehran,IR", "Hanoi,VN", "Bangalore,IN", "Barcelona,ES", "Berlin,DE", "Cape Town,ZA",
    "Chicago,US", "Dubai,AE", "Dublin,IE", "Edinburgh,GB", "Frankfurt,DE", "Geneva,CH",
    "Havana,CU", "Helsinki,FI", "Hong Kong,HK", "Honolulu,US", "Kingston,JM", "Kuala Lumpur,MY",
    "Lisbon,PT", "London,GB", "Madrid,ES", "Melbourne,AU", "Milan,IT", "Montreal,CA", "Nairobi,KE",
    "Nashville,US", "New Orleans,US", "Oslo,NO", "Paris,FR", "Prague,CZ", "Reykjavik,IS", "Rome,IT",
    "San Francisco,US", "Singapore,SG", "Stockholm,SE", "Sydney,AU", "Taipei,TW", "Toronto,CA", "Vancouver,CA",
    "Vienna,AT", "Warsaw,PL", "Zurich,CH", "Amsterdam,NL", "Athens,GR", "Brussels,BE", "Budapest,HU", 
    "Copenhagen,DK", "Dubrovnik,HR", "Kyiv,UA", "Luxembourg City,LU", "Munich,DE", "Nice,FR", "Nicosia,CY",
    "Ottawa,CA", "Riga,LV", "St. Petersburg,RU", "Tallinn,EE", "Valletta,MT", "Vilnius,LT", 
    "Wellington,NZ", "Zagreb,HR", "Albuquerque,US", "Anchorage,US", "Asheville,US", "Austin,US", "Baltimore,US",
    "Birmingham,US", "Boise,US", "Boston,US", "Charleston,US", "Charlotte,US", "Chattanooga,US", "Cincinnati,US",
    "Cleveland,US", "Columbia,US", "Columbus,US", "Dallas,US", "Denver,US", "Des Moines,US", "Detroit,US",
    "El Paso,US", "Fargo,US", "Fort Wayne,US", "Fresno,US", "Greensboro,US", "Harrisburg,US", "Houston,US",
    "Indianapolis,US", "Jacksonville,US", "Kansas City,US", "Las Vegas,US", "Little Rock,US",
    "Louisville,US", "Memphis,US", "Miami,US", "Milwaukee,US", "Minneapolis,US", "Norfolk,US",
    "Oklahoma City,US", "Omaha,US", "Orlando,US", "Philadelphia,US", "Phoenix,US", "Pittsburgh,US",
    "Portland,US", "Providence,US", "Raleigh,US", "Richmond,US", "Riverside,US", "Rochester,US",
    "Sacramento,US", "Salt Lake City,US", "San Antonio,US", "San Diego,US", "San Francisco,US",
    "San Jose,US", "Sarasota,US", "Seattle,US", "Spokane,US", "St. Louis,US", "Syracuse,US",
    "Tampa,US", "Toledo,US", "Tucson,US", "Tulsa,US", "Virginia Beach,US", "Washington,US",
    "Wichita,US", "Sofia,BG", "Calgary,CA", "Montréal,CA", "Santiago,CL", "Jerusalem,IL",
    "Kuala Lumpur,MY", "Riyadh,SA", "Johannesburg,ZA", "Seoul,KR", "Stockholm,SE",
];
